FROM golang:1.22-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/orderbook-service ./cmd/orderbook

FROM alpine:3.19
RUN apk add --no-cache ca-certificates

COPY --from=builder /app/orderbook-service /orderbook-service
ENTRYPOINT ["/orderbook-service"]
